- name: Run using a project directory
  hosts: all
  gather_facts: no
  tasks:
    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: /fan-gen
        state: absent

    - name: Prune everything
      docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
        
    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: /fan-gen
        build: yes
      register: output

    - ansible.builtin.debug:
        var: output

    - ansible.builtin.assert:
        that:
          - "fan_gen.service_1.state.running"
          - "fan_gen.service_2.state.running"
          - "fan_gen.service_3.state.running"
          - "fan_gen.service_4.state.running"